// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID         int64
	Amount     int64
	SenderID   int64
	ReceiverID int64
	CreatedAt  time.Time
}

type User struct {
	UserName          string
	FullName          string
	Password          string
	Email             string
	CreatedAt         time.Time
	PasswordChangedAt time.Time
}
