services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      #current root folder
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:postgres@postgresql:5432/simple_bank?sslmode=disable
    depends_on:
      - postgresql
    entrypoint: ["/app/wait-for.sh", "postgresql:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
