# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: checkout code in the go module directory
        uses: actions/checkout@v3

      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: run migrations
        run: goose -dir sql/schema postgres postgres://root:postgres@localhost:5432/simple_bank up
      - name: Test
        env:
          DB_URL: ${{secrets.DB_URL}}
        run: make test
